variables:
  PROJECT_NAME: watchers
  ROOTPATH: /go/src/git.posc.in/cw
  GO_IMAGE: registry.posc.in/cw/infra/go

stages:
  - test

image: $GO_IMAGE

before_script:
  - mkdir -p ${ROOTPATH}
  - cp -r $CI_PROJECT_DIR ${ROOTPATH}/${PROJECT_NAME}
  - make dep

# Run local tests
local:
  stage: test
  script:
    - make lint
    - make test

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master
